### ISSUE TITLE
Example App Not Working

### ISSUE THREAD

**Issue by andersonnatt** [VVyacheslav/django-rest-framework-datatables-editor#1]
After cloning the example app and following the directions to replace the .js files (with my own paid version from Datatables.net) I'm unable to edit or delete data.  Any help is greatly appreciated.

**Comment by VVyacheslav** [comment]
Can you give me more information? What messages are in the browser console? What messages are there in Django?

**Comment by andersonnatt** [comment]
The tables all load fine, and I can select a record to edit.  A modal pops up and I can enter the information that I want to change, and I get an error when I click ‘Update’.  In the browser it says ‘a system error has occurred and has a link to the data tables.net site.  In my console I get an 500 and it says the ‘Artist’ object is not iterable.

Thanks for your help.  I really appreciate it and look forward to this working!

Nat

**Comment by VVyacheslav** [comment]
I tested cloning and running the sample application again and everything works.
Did you use virtualenv? if you haven't used it, please try using.
If this does not help, please email me at vvvyacheslav23@gmail.com and i will try to help you.

**Comment by andersonnatt** [comment]
Ok. I am using a virtual env. I’ll try again and email with more details if I have trouble. Thanks for all your work and all your help. I greatly appreciate it!!

Nat
