### ISSUE TITLE
Pulling request parameters from ajax

### ISSUE THREAD

**Issue by nanomancy** [VVyacheslav/django-rest-framework-datatables-editor#11]
Is there any way to pull request parameter from ajax request?
This is to be used for filtering queryset (searching by date from a large table).

I'm primarily using the sample views from example project, and I couldn't find way to call request object in ModelViewSet class.

> class AlbumViewSet(DatatablesEditorModelViewSet):
    queryset = Album.objects.all().order_by('rank')
    serializer_class = AlbumSerializer

>    def get_options(self):
        return get_album_options()

>    class Meta:
        datatables_extra_json = ('get_options', )

Thank you!

Edit: This is so that I can use Editor with server-side processing off in order to allow printing/exporting all pages of query result, as well as edit fields. With server-side off, I need a way to filter the initial query, otherwise it takes ages to load the full table.

**Comment by VVyacheslav** [comment]
I think I don't quite understand you. From the method in the `ViewSet`, you can access the `request` through `self.request`.

**Comment by nanomancy** [comment]
Apologies if this is a simple problem.
Would you mind showing me a DatatablesEditorModelViewSet class using request? 
I tried self.request or viewsets.request, but they can't find request attribute.
