### ISSUE TITLE
editor.inline support

### ISSUE THREAD

**Issue by diogosimao** [VVyacheslav/django-rest-framework-datatables-editor#3]
How about support in order to deal with anything like:
> 
>     $('#albums').on( 'click', 'tbody td:not(:first-child)', function (e) {
>         editor.inline( this );
>     } );
> 
> 

?

I have seen on `/example/albums/templates/albums/albums.html` that is possible to add this lines in order to turn datatable cell editable. My question is: how is it supported on DRF?

**Comment by VVyacheslav** [comment]
Hi.
It depends on datatable editor, and not not on DRF or django-rest-framework-datatables-editor. You can use inline editing.
