### ISSUE TITLE
Online documentation is out of date and documentation doesn't build

### ISSUE THREAD

**Issue by ve3jrw** [VVyacheslav/django-rest-framework-datatables-editor#9]
https://drf-datatables-editor.readthedocs.io/en/latest/tutorial.html

Isn't the latest documentation, it is missing CSRF info for example.

The documentation fails to build:

(env_mm) cwelch@django:~/DRF-datatables-editor/docs$ !make
make html
Running Sphinx v1.6.7
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 6 source files that are out of date
updating environment: 6 added, 0 changed, 0 removed
reading sources... [100%] tutorial                                                                                                              

Sphinx error:
master file /home/cwelch/DRF-datatables-editor/docs/contents.rst not found
Makefile:19: recipe for target 'html' failed
make: *** [html] Error 1

**Comment by VVyacheslav** [comment]
@ve3jrw Thank you for noticing that. I have updated the documentation and Sphinx requirements. Now everything is correct.
